### PR TITLE
Make resolve() abstract, make dereference() concrete

### PR DESCRIPTION
**Pull request by peacekeeper**
PR for internal review. Do not merge..

### CODE REVIEW

**Comment by dlongley** [comment]
I was thinking that another less invasive approach to reach a compromise would be:

1. Use the [Infra](https://infra.spec.whatwg.org/) spec to describe all types for inputs and outputs for `resolve`.
2. Indicate that the input to `resolve` is a [string](https://infra.spec.whatwg.org/#strings) for the `did` and a [map](https://infra.spec.whatwg.org/#maps) for the `did-resolution-input-metadata`.
3. Indicate that the outputs of `resolve` depend on a desired type expressed in the `did-resolution-input-metadata` such that the `did-document` is a [map](https://infra.spec.whatwg.org/#maps), if no concrete representation was expressed in `did-resolution-input-metadata` (via a mime type), or it is a [byte sequence](https://infra.spec.whatwg.org/#byte-sequences) if one was specified. The `did-document-metadata` and `did-resolution-metadata` would both always be [maps](https://infra.spec.whatwg.org/#maps).

**Comment by dlongley** [comment]
What do you think of the above [proposal](https://github.com/peacekeeper/did-core/pull/2#issuecomment-645048614), @peacekeeper?

**Comment by peacekeeper** [comment]
I guess that could work too, so the `accept` input metadata property would be optional. If it's present -> byte sequence. If it's not present -> did document abstract data model.

**Comment by dlongley** [comment]
> I guess that could work too, so the accept input metadata property would be optional. If it's present -> byte sequence. If it's not present -> did document abstract data model.

Yes, I think a simple change like that could get us to consensus with a single function that is both implementable by all current DID resolvers and testable.

**Comment by peacekeeper** [comment]
Thanks for the input, I will close this and create PRs in the upstream repo.

**Pull request closed without merging**
